name: H3_indicators
channels:
  - conda-forge
dependencies:
  - geopandas[version='>=0.13.2']
  - pandas
  - python=3.12
  - h3
  - pyarrow
  - h3-py=3.7.7
  - geojson
  - fastparquet
  - ipykernel
  - h3pandas
  - dask
  - dask-geopandas